export interface SystemMetric {
  id: string
  label: string
  value: number
  unit: string
  trend: 'up' | 'down' | 'steady'
  delta: number
  description: string
}

export const systemMetrics: SystemMetric[] = [
  {
    id: 'active-loops',
    label: 'Active Learning Loops',
    value: 3,
    unit: '',
    trend: 'up',
    delta: 1,
    description: 'Residual orchestration currently tracks three feedback loops.'
  },
  {
    id: 'uncertainty-drop',
    label: 'Uncertainty Drop',
    value: 37,
    unit: '%',
    trend: 'down',
    delta: 12,
    description: 'Overall epistemic uncertainty reduced after the latest acquisition.'
  },
  {
    id: 'auto-labeled',
    label: 'Auto-Labeled Samples',
    value: 9850,
    unit: '',
    trend: 'up',
    delta: 620,
    description: 'High quality pseudo labels generated by the Quality Guardian MCP tool.'
  },
  {
    id: 'deployment-latency',
    label: 'Deployment Latency',
    value: 450,
    unit: 'ms',
    trend: 'steady',
    delta: 5,
    description: 'Average inference latency for the currently deployed model.'
  }
]

